services:
  - docker
language: python
python:
  - "3.5"
env:
  - SCIROCCO_DOCKER_HOST_PORT=80
  - SCIROCCO_PORT=8000
  - SCIROCCO_MONGO_URL=mongodb://scirocco-db/scirocco-server
# command to install dependencies
install:
  - git clone https://github.com/eloylp/scirocco-server.git
  - docker-compose -f scirocco-server/srv_scirocco-server/docker-compose.yml up -d --build
  - sleep 10s
  - pip3 install .
  - pip3 install -r requirements.txt
# command to run tests
script: python3 setup.py test
